[package]
name = "rust-web-app"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
argon2 = "0.5.3"
chrono = {version = "0.4.41", features = ["serde"]}
diesel = { version = "2.2.12", features = ["r2d2", "sqlite"] }
dotenvy = "0.15.7"
rand_core= {version = "0.6", features = ["getrandom"]} 
jsonwebtoken = "9.3.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
futures = "0.3.31"
actix-cors = "0.7.1"
